### ISSUE TITLE
No code included in node_modules

### ISSUE THREAD

**Issue by sillvva** [fredericoo/drizzle-toolbelt#3]
It's just the package.json and readme.md

![image](https://github.com/fredericoo/drizzle-toolbelt/assets/5138384/b4b09992-c80d-44f3-8a39-4cdab90a2795)

And when I import it, I get this:

```
Cannot find module 'drizzle-toolbelt' or its corresponding type declarations.
```

I tried both npm and pnpm

**Comment by fredericoo** [comment]
LOL I’m so sorry! I guess by testing locally I shot myself in the foot.

I’ve now corrected it and you should see the files as per 1.1.1. Let me know if it still doesn’t work.

**Comment by sillvva** [comment]
Yep that fixed it, though aggregateRows is not exported

**Comment by sillvva** [comment]
Oh, nevermind. The readme shows an `aggregateRows` function, but it's probably supposed to be `aggregate`.
